---
######################################################
# GameCraftPEStaff Created by TheDeibo, and Driesboy #
######################################################
#
#@@@@@@@@@@@@@@@@@@@@@@@@@@#
#          YOUTUBE         #
#@@@@@@@@@@@@@@@@@@@@@@@@@@#
#
yt1: "Our Youtube is"
yt2: "https://goo.gl/WhS1nw"
#
# Shortened the URL.
#
#@@@@@@@@@@@@@@@@@@@@@@@@@@#
#           GitHub         #
#@@@@@@@@@@@@@@@@@@@@@@@@@@#
#
git1: "Our GitHub is"
git2: "https://github.com/GameCraftPE"
#
#@@@@@@@@@@@@@@@@@@@@@@@@@@#
#         FACEBOOK         #
#@@@@@@@@@@@@@@@@@@@@@@@@@@#
#
fb1: "Our Facebook Is"
fb2: "www.facebook.com/gamecraftpe"
#
#@@@@@@@@@@@@@@@@@@@@@@@@@@#
#           Website       #
#@@@@@@@@@@@@@@@@@@@@@@@@@@#
#
web1: "Our Website is"
web2: "www.gamecraftpe.tk/"
#
#If you require more social Media,
#you will need to edit the plugin, 
#or contact Driesboy or TheDeibo!
#
#Please do not add more Staff slots!
#It may corrupt the config file!
...
